### PR TITLE
Fix grab screenshot

### PR DESCRIPTION
**Pull request by mapulu**
Using bearer and hardware id=cloud id for authentification

### CODE REVIEW

**Comment by denniedegroot** [comment]
Thanks for the pull request! I will take a look at it tonight or tomorrow.

**Comment by mapulu** [comment]
It still needs some additional steps for checking if the bearer token is still valid. Also taking snapshots takes more time then 3x1 second for me

**Comment by denniedegroot** [comment]
Ah ok, please let me know when you are finished.

**Comment by mapulu** [comment]
Should be over the next week.
Seems the bearer token is only valid for some hours. But that token is needed for taking/grabbing snapshots.

**Comment by mapulu** [comment]
Finished... It now fetches a new bearer token when not valid for snapshots, might not look so nice but works.

**Comment by denniedegroot** [comment]
I just merged it in the beta branch and did a quick review. Is the login still working because I see you disabled a authorization line? Can you test this? (So logout/login with your Ring credentials.)

**Comment by mapulu** [comment]
It should still work to login/logout. I will test it.
The authorization line does not work anymore so I removed it. They changed their api. The Bearer token is used instead

**Comment by denniedegroot** [comment]
Can you test my beta branch just to confirm everything merged well?

**Comment by mapulu** [comment]
yes after the weekend

**Comment by SiobhanBaynes** [comment]
Just tested this on the beta branch and it seems to be working great.  Did get an error the first time I ran it (log available if you want it) but ran again and all seems fine. Thanks guys 🙂

**Comment by SiobhanBaynes** [comment]
Raised a PR to fix the error I was seeing.  I'm not seeing the image in the Flow to send the notification.  I can only see it on the developer portal/

**Comment by mapulu** [comment]
@SiobhanBaynes did you use for the "image was grabbed" the mobile notification? If you use iOs you also have to enter a text to send.


The PR from @SiobhanBaynes fixes an issue when a valid answer for timestamp was send but no timestamp in it

**Comment by SiobhanBaynes** [comment]
@mapulu No I wasn't. I was trying to send the image in the same flow that grabbed it.  Using the image was grabbed notification it's working fine 👌

**Comment by mapulu** [comment]
Sending the image in the same flow which grabbed it do not really work. Also the same with the image grabber app.

**Pull request merged**
