### PR TITLE
added support for siren/floodlights on stickupcam

### PR DESCRIPTION
**Pull request by kaohlive**
Added support for authorized_doorbell collection
and support for floodlights and sirens on stickupcams

### CODE REVIEW

**Comment by denniedegroot** [comment]
Why did you lower the refreshDevicesInterval?

**Comment by kaohlive** [comment]
As far as I could tell there was no other event that shows the status of the Alarm and Light of the stickup cams. So to get a semi reliable state in case the trigger was done in a non homey app source the once per hour was to little. Not sure if it can cause side effects. As far as I can tell on my system the devices seem to work properly.

**Comment by denniedegroot** [comment]
One side effect is that is causes 10x more (small) traffic to Ring. But I don't think it should cause an issue. I will leave it in for now.

**Comment by kaohlive** [comment]
If you need my feedback before you send it to Homey please let me know. It has been running on my homey for a week without issue (still suffer myself from the snapshot often not loading but thats an API thing from the start).

**Pull request merged**
