### PR TITLE
Stickup cam enable/disable motion detection

### LINKED ISSUE #43: Motion on/off does not work
To set the motion detection on or off Via a flow does not work for the stick up cam.

### PR DESCRIPTION
**Pull request by tokreutz**
Was able to reverse engineer the Ring APIs and found the proper Ring endpoint for enabling/disabling motion detection for the stickup cams.

I have validated this with my own Homey and stickup cam, and seems to work as expected.

Should resolve #43

### CODE REVIEW

**Comment by tokreutz** [comment]
@denniedegroot is it possible to get a review on this one?

**Comment by denniedegroot** [comment]
Hi, thanks for your great work! I see you are working on a better solution based on a different library, am I right?

**Comment by tokreutz** [comment]
Yes. I want to integrate using the dgrief/ring project. It has most, if not all of Rings APIs covered. Integrating that will take a little time, but I expect we can use that for all Ring interaction over time. Currently working on mode support.

As it might take a while doing that I suggest we complete this PR to get the functionality fixed for the motion detection. I will open new PRs for that as I get more done om that integration. Might need a few more devices also :p

**Comment by tokreutz** [comment]
@denniedegroot , one question. how did you come across the icons used for the cameras, or did you create them yourself?

**Comment by edwinvdpol** [comment]
https://github.com/athombv/homey-vectors-public/tree/master/com.ring

**Comment by tokreutz** [comment]
Thanks @edwinvdpol , but who has created these? What I'm really after is tips for creating an icon for the alarm mode support I'm adding.

**Comment by edwinvdpol** [comment]
I _think_ Ivo Derksen, as he created all the icons which are found [here](https://github.com/athombv/homey-vectors-public).

**Comment by tokreutz** [comment]
I have already tested the functionality, and it works as expected. Thanks @mhoogenbosch  for the offer. Maybe I can ask for testing assistance for future PRs to this project :)

Just waiting for @denniedegroot  to merge the request as I don't have the power to do so myself.

**Comment by denniedegroot** [comment]
@tokreutz are you maybe willing to take over the app as I don’t have much spare time or Ring devices?

**Comment by tokreutz** [comment]
@denniedegroot , sure. I can do that :) 
Is there any formal way of doing so?

**Comment by denniedegroot** [comment]
@tokreutz I will check how I can do it.

Meanwhile could someone verify if it is working as intended? https://homey.app/a/com.amazon.ring/test/

**Pull request merged**
