### PR TITLE
Add support for Camera image page on doorbell device

### PR DESCRIPTION
**Pull request by kaohlive**
Added support to fill the camera view page of the doorbell device. It loads with the ring logo but when the GrabImage flow action card gets called the latest snapshot image will be displayed on the device. 
Also replaced the image object with a single reference with update mechanism.

Todo: image uses setBuffer and should be setStream. I cant make the setStream work.

### CODE REVIEW

**Comment by kaohlive** [comment]
Made an update to handle a missing snapshot returning 404 as resource not found error instead of invalid authentication

**Comment by denniedegroot** [comment]
Thanks again! I will have a look at it tonight.
Could you maybe next time don't change the version number as more fixes might me merged before a new version is released.

**Comment by kaohlive** [comment]
Sorry will do :) not very experienced in the git method. Learning on the job.

**Comment by denniedegroot** [comment]
No problem, you are doing a great job!
Could you test the test build? https://homey.app/a/com.amazon.ring/test/

**Comment by kaohlive** [comment]
Looks good on first impression, now my device gives a 404 all the time, probably that due to the corona no one rings the door anymore

**Pull request merged**
