### PR TITLE
refactor on camera/grab image.

### PR DESCRIPTION
**Pull request by kaohlive**
Removed now deprecated image.fromBuffer and replaced it with setStream where the stream is not tied to the grabimage api call.
This improves the cameraview page so that the refresh button now actually updates the images from the API instead of from memory.
The grabImage action now only refreshes the cameraview also, the image grabbed event than takes that images.
Cleaner code and more funcitonality with no more deprecated methods.

Also put all this code in the stickupcam device, no idea if it works though, I do not have one.

### CODE REVIEW

**Comment by kaohlive** [comment]
its ready for you to merge this one.

**Comment by denniedegroot** [comment]
Hi @kaohlive, I cannot merge this one as it has conflicts. Can you rebase based on the master branch?

**Comment by kaohlive** [comment]
@denniedegroot sorry, git is not my friend. So I messsed up the version again I think. But it says at least there is no merge conflict anymore.

**Comment by kaohlive** [comment]
just in case it was not clear 😉 i rebased and solved the conflicts. so you should be able to merge.

**Comment by denniedegroot** [comment]
Thanks again!

**Pull request merged**
